### ISSUE TITLE
Error while docker compose

### ISSUE THREAD

**Issue by deepaklive** [etiennedi/keycloak-nginx-https-self#1]
Step 3/4 : COPY cert.crt /etc/nginx/cert.crt
ERROR: Service 'nginx' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder015628708/cert.crt: no such file or directory

I am using docker for windows.. Please Help

**Comment by etiennedi** [comment]
Your docker build is failing because it can't find the certificate.

Please see the readme for the required steps to run before `docker-compose up`. Step 1 creates a CA, step 2 self-signs a cert with the CA created in step 1. The script generates the file at `cert.crt` ([as you can see here](https://github.com/etiennedi/keycloak-nginx-https-self/blob/9af1d0a0d31ecafc51f028cdf80737c3c189deb7/issue_cert.sh#L7)).

Once you created all the files, the docker build step should work fine.
